// Generated by CoffeeScript 1.6.3
(function() {
  window.SR || (window.SR = {});

  SR.Histogram = (function() {
    function Histogram(element) {
      this.initialize_svg(element);
    }

    Histogram.prototype.initialize_svg = function(element) {
      console.log('initialize_svg', element);
      return this.svg = d3.select(element).append('svg');
    };

    return Histogram;

  })();

}).call(this);
