// Generated by CoffeeScript 1.6.3
(function() {
  window.histogram = new SR.Histogram('#histogram');

  d3.json("data/histograms.json", function(error, json) {
    console.log(error);
    histogram.data(json);
    return histogram.render();
  });

}).call(this);
